#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: $0 <number> <name>"
    echo "Example: $0 1 two-sum"
    exit 1
fi

NUM=$(printf "%04d" "$1")
NAME="$2"
DIR="problems/${NUM}-${NAME}"

if [ -d "$DIR" ]; then
    echo "Problem $DIR already exists!"
    echo "Opening: $DIR/sol.cpp"
    exec "${EDITOR:-nvim}" "$DIR/sol.cpp"
fi

mkdir -p "$DIR"
cat > "$DIR/sol.cpp" << 'TEMPLATE'
#include "lc.hpp"

class Solution {
  public:
    // TODO: paste method signature here
};

int main() {
    Solution s;

    // test cases
    // example:
    //
    // ordered:
    //
    // std::vector<int> t1{1, 2, 3, 1};
    // expect(s.containsDuplicate(t1), true);
    //
    // unordered:
    //
    // std::vector<int> n1 = {2, 7, 11, 15};
    // int t1 = 9;
    // std::vector<int> e = {0, 1};
    // expect_unordered(s.twoSum(n1, t1), {0, 1});

    return 0;
}
TEMPLATE

echo "Created $DIR/sol.cpp"
exec "${EDITOR:-nvim}" "$DIR/sol.cpp"
