#!/bin/zsh

local file="${1:-$(find problems -name 'sol.cpp' -printf '%T@ %p\n' | sort -rn | head -1 | cut -d' ' -f2)}"
if [ -z "$file" ]; then
echo "no solution files found"
return 1
fi
echo "── Running: $file ──"
make run F="$file" "${@:2}"
